In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv('../data/florida_dataset.csv')

In [7]:
df.head()

,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,ROUTE_NUMBER_005D,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,...,BRIDGE_LEN_IND_112,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,FED_AGENCY,SUBMITTED_BY,BRIDGE_CONDITION,LOWEST_RATING,DECK_AREA
0,12,10001,1,2,1,00041,0,1,15,0,...,Y,8,52050,2043,0.0,N,12,G,7,191.80
1,12,10003,1,4,1,00074,0,1,15,0,...,Y,8,9196,2042,0.0,N,12,F,6,113.36
2,12,10006,1,4,2,0765A,0,1,15,0,...,Y,8,9890,2042,0.0,N,12,G,7,69.58
3,12,10007,1,4,1,00764,0,1,15,0,...,Y,8,3593,2042,0.0,N,12,F,6,356.46
4,12,10008,1,4,1,00764,0,1,15,0,...,Y,8,1509,2042,0.0,N,12,F,6,385.52

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3417 entries, 0 to 3416
Columns: 123 entries, STATE_CODE_001 to DECK_AREA
dtypes: float64(37), int64(52), object(34)
memory usage: 3.2+ MB

In [10]:
df.shape

(3417, 123)

In [11]:
df.describe()

,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,CRITICAL_FACILITY_006B,...,YEAR_RECONSTRUCTED_106,PERCENT_ADT_TRUCK_109,NATIONAL_NETWORK_110,PIER_PROTECTION_111,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,SUBMITTED_BY,LOWEST_RATING,DECK_AREA
count,3417.0,3417.000000,3417.0,3417.000000,3417.000000,3417.000000,3417.000000,3417.000000,3417.000000,0.0,...,3417.000000,3417.000000,3417.000000,156.000000,3417.000000,3417.000000,3417.000000,3417.0,3417.000000,3417.000000
mean,12.0,100839.302605,1.0,3.304068,1.386596,0.006146,3.965759,63.692420,23035.097454,NaN,...,378.014633,9.139596,0.198420,1.826923,29319.341528,2042.093942,0.002692,12.0,6.650278,1386.994838
std,0.0,45590.298030,0.0,1.447063,1.455055,0.146056,3.031692,28.999666,28760.172651,NaN,...,782.319454,7.633404,0.398868,0.843674,40795.158550,1.274737,0.107444,0.0,0.736129,5756.164352
min,12.0,10001.000000,1.0,1.000000,0.000000,0.000000,1.000000,15.000000,0.000000,NaN,...,0.000000,0.000000,0.000000,1.000000,0.000000,2021.000000,0.000000,12.0,2.000000,22.320000
25%,12.0,70059.000000,1.0,2.000000,1.000000,0.000000,1.000000,51.000000,0.000000,NaN,...,0.000000,4.000000,0.000000,1.000000,3470.000000,2042.000000,0.000000,12.0,6.000000,157.990000
50%,12.0,104356.000000,1.0,4.000000,1.000000,0.000000,1.000000,57.000000,0.000000,NaN,...,0.000000,7.000000,0.000000,2.000000,13375.000000,2042.000000,0.000000,12.0,7.000000,421.120000
75%,12.0,135001.000000,1.0,4.000000,1.000000,0.000000,7.000000,81.000000,56975.000000,NaN,...,0.000000,13.000000,0.000000,2.000000,36960.000000,2043.000000,0.000000,12.0,7.000000,1041.400000
max,12.0,164301.000000,1.0,8.000000,8.000000,4.000000,8.000000,105.000000,79250.000000,NaN,...,2022.000000,90.000000,1.000000,5.000000,281938.000000,2043.000000,5.600000,12.0,9.000000,193374.900000

In [13]:
df.isnull().sum()

STATE_CODE_001          0
STRUCTURE_NUMBER_008    0
RECORD_TYPE_005A        0
ROUTE_PREFIX_005B       0
SERVICE_LEVEL_005C      0
                       ..
FED_AGENCY              0
SUBMITTED_BY            0
BRIDGE_CONDITION        0
LOWEST_RATING           0
DECK_AREA               0
Length: 123, dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.corr

<bound method DataFrame.corr of       STATE_CODE_001  STRUCTURE_NUMBER_008  RECORD_TYPE_005A  \
0                 12                 10001                 1
1                 12                 10003                 1
2                 12                 10006                 1
3                 12                 10007                 1
4                 12                 10008                 1
...              ...                   ...               ...
3412              12                164221                 1
3413              12                164222                 1
3414              12                164223                 1
3415              12                164229                 1
3416              12                164301                 1

      ROUTE_PREFIX_005B  SERVICE_LEVEL_005C ROUTE_NUMBER_005D  DIRECTION_005E  \
0                     2                   1             00041               0
1                     4                   1             00074               0
2                     4                   2             0765A               0
3                     4                   1             00764               0
4                     4                   1             00764               0
...                 ...                 ...               ...             ...
3412                  4                   1             00000               0
3413                  4                   1             00000               0
3414                  4                   1             00000               0
3415                  4                   1             CR544               0
3416                  4                   1             00000               0

      HIGHWAY_DISTRICT_002  COUNTY_CODE_003  PLACE_CODE_004  ...  \
0                        1               15               0  ...
1                        1               15               0  ...
2                        1               15               0  ...
3                        1               15               0  ...
4                        1               15               0  ...
...                    ...              ...             ...  ...
3412                     1              105               0  ...
3413                     1              105               0  ...
3414                     1              105           78275  ...
3415                     1              105           28400  ...
3416                     1              105               0  ...

     BRIDGE_LEN_IND_112  SCOUR_CRITICAL_113 FUTURE_ADT_114  \
0                     Y                   8          52050
1                     Y                   8           9196
2                     Y                   8           9890
3                     Y                   8           3593
4                     Y                   8           1509
...                 ...                 ...            ...
3412                  Y                   8          24464
3413                  Y                   8           6940
3414                  Y                   8           7634
3415                  Y                   8           3527
3416                  Y                   U           4489

     YEAR_OF_FUTURE_ADT_115  MIN_NAV_CLR_MT_116  FED_AGENCY  SUBMITTED_BY  \
0                      2043                 0.0           N            12
1                      2042                 0.0           N            12
2                      2042                 0.0           N            12
3                      2042                 0.0           N            12
4                      2042                 0.0           N            12
...                     ...                 ...         ...           ...
3412                   2042                 0.0           N            12
3413                   2042                 0.0           N            12
3414                   2042                 0.0           N            12
3415                   2042                 0.0           N            12
3416                   2042                 0.0           N            12

      BRIDGE_CONDITION  LOWEST_RATING  DECK_AREA
0                    G              7     191.80
1                    F              6     113.36
2                    G              7      69.58
3                    F              6     356.46
4                    F              6     385.52
...                ...            ...        ...
3412                 F              6     358.94
3413                 F              6     358.94
3414                 G              7     128.38
3415                 G              7     263.61
3416                 F              6     118.08

[3417 rows x 123 columns]>

In [22]:
df.value_counts

<bound method DataFrame.value_counts of       STATE_CODE_001  STRUCTURE_NUMBER_008  RECORD_TYPE_005A  \
0                 12                 10001                 1
1                 12                 10003                 1
2                 12                 10006                 1
3                 12                 10007                 1
4                 12                 10008                 1
...              ...                   ...               ...
3412              12                164221                 1
3413              12                164222                 1
3414              12                164223                 1
3415              12                164229                 1
3416              12                164301                 1

      ROUTE_PREFIX_005B  SERVICE_LEVEL_005C ROUTE_NUMBER_005D  DIRECTION_005E  \
0                     2                   1             00041               0
1                     4                   1             00074               0
2                     4                   2             0765A               0
3                     4                   1             00764               0
4                     4                   1             00764               0
...                 ...                 ...               ...             ...
3412                  4                   1             00000               0
3413                  4                   1             00000               0
3414                  4                   1             00000               0
3415                  4                   1             CR544               0
3416                  4                   1             00000               0

      HIGHWAY_DISTRICT_002  COUNTY_CODE_003  PLACE_CODE_004  ...  \
0                        1               15               0  ...
1                        1               15               0  ...
2                        1               15               0  ...
3                        1               15               0  ...
4                        1               15               0  ...
...                    ...              ...             ...  ...
3412                     1              105               0  ...
3413                     1              105               0  ...
3414                     1              105           78275  ...
3415                     1              105           28400  ...
3416                     1              105               0  ...

     BRIDGE_LEN_IND_112  SCOUR_CRITICAL_113 FUTURE_ADT_114  \
0                     Y                   8          52050
1                     Y                   8           9196
2                     Y                   8           9890
3                     Y                   8           3593
4                     Y                   8           1509
...                 ...                 ...            ...
3412                  Y                   8          24464
3413                  Y                   8           6940
3414                  Y                   8           7634
3415                  Y                   8           3527
3416                  Y                   U           4489

     YEAR_OF_FUTURE_ADT_115  MIN_NAV_CLR_MT_116  FED_AGENCY  SUBMITTED_BY  \
0                      2043                 0.0           N            12
1                      2042                 0.0           N            12
2                      2042                 0.0           N            12
3                      2042                 0.0           N            12
4                      2042                 0.0           N            12
...                     ...                 ...         ...           ...
3412                   2042                 0.0           N            12
3413                   2042                 0.0           N            12
3414                   2042                 0.0           N            12
3415                   2042                 0.0           N            12
3416                   2042                 0.0           N            12

      BRIDGE_CONDITION  LOWEST_RATING  DECK_AREA
0                    G              7     191.80
1                    F              6     113.36
2                    G              7      69.58
3                    F              6     356.46
4                    F              6     385.52
...                ...            ...        ...
3412                 F              6     358.94
3413                 F              6     358.94
3414                 G              7     128.38
3415                 G              7     263.61
3416                 F              6     118.08

[3417 rows x 123 columns]>

In [23]:
df.astype

<bound method NDFrame.astype of       STATE_CODE_001  STRUCTURE_NUMBER_008  RECORD_TYPE_005A  \
0                 12                 10001                 1
1                 12                 10003                 1
2                 12                 10006                 1
3                 12                 10007                 1
4                 12                 10008                 1
...              ...                   ...               ...
3412              12                164221                 1
3413              12                164222                 1
3414              12                164223                 1
3415              12                164229                 1
3416              12                164301                 1

      ROUTE_PREFIX_005B  SERVICE_LEVEL_005C ROUTE_NUMBER_005D  DIRECTION_005E  \
0                     2                   1             00041               0
1                     4                   1             00074               0
2                     4                   2             0765A               0
3                     4                   1             00764               0
4                     4                   1             00764               0
...                 ...                 ...               ...             ...
3412                  4                   1             00000               0
3413                  4                   1             00000               0
3414                  4                   1             00000               0
3415                  4                   1             CR544               0
3416                  4                   1             00000               0

      HIGHWAY_DISTRICT_002  COUNTY_CODE_003  PLACE_CODE_004  ...  \
0                        1               15               0  ...
1                        1               15               0  ...
2                        1               15               0  ...
3                        1               15               0  ...
4                        1               15               0  ...
...                    ...              ...             ...  ...
3412                     1              105               0  ...
3413                     1              105               0  ...
3414                     1              105           78275  ...
3415                     1              105           28400  ...
3416                     1              105               0  ...

     BRIDGE_LEN_IND_112  SCOUR_CRITICAL_113 FUTURE_ADT_114  \
0                     Y                   8          52050
1                     Y                   8           9196
2                     Y                   8           9890
3                     Y                   8           3593
4                     Y                   8           1509
...                 ...                 ...            ...
3412                  Y                   8          24464
3413                  Y                   8           6940
3414                  Y                   8           7634
3415                  Y                   8           3527
3416                  Y                   U           4489

     YEAR_OF_FUTURE_ADT_115  MIN_NAV_CLR_MT_116  FED_AGENCY  SUBMITTED_BY  \
0                      2043                 0.0           N            12
1                      2042                 0.0           N            12
2                      2042                 0.0           N            12
3                      2042                 0.0           N            12
4                      2042                 0.0           N            12
...                     ...                 ...         ...           ...
3412                   2042                 0.0           N            12
3413                   2042                 0.0           N            12
3414                   2042                 0.0           N            12
3415                   2042                 0.0           N            12
3416                   2042                 0.0           N            12

      BRIDGE_CONDITION  LOWEST_RATING  DECK_AREA
0                    G              7     191.80
1                    F              6     113.36
2                    G              7      69.58
3                    F              6     356.46
4                    F              6     385.52
...                ...            ...        ...
3412                 F              6     358.94
3413                 F              6     358.94
3414                 G              7     128.38
3415                 G              7     263.61
3416                 F              6     118.08

[3417 rows x 123 columns]>

In [25]:
print(df.columns.tolist())

['STATE_CODE_001', 'STRUCTURE_NUMBER_008', 'RECORD_TYPE_005A', 'ROUTE_PREFIX_005B', 'SERVICE_LEVEL_005C', 'ROUTE_NUMBER_005D', 'DIRECTION_005E', 'HIGHWAY_DISTRICT_002', 'COUNTY_CODE_003', 'PLACE_CODE_004', 'FEATURES_DESC_006A', 'CRITICAL_FACILITY_006B', 'FACILITY_CARRIED_007', 'LOCATION_009', 'MIN_VERT_CLR_010', 'KILOPOINT_011', 'BASE_HWY_NETWORK_012', 'LRS_INV_ROUTE_013A', 'SUBROUTE_NO_013B', 'LAT_016', 'LONG_017', 'DETOUR_KILOS_019', 'TOLL_020', 'MAINTENANCE_021', 'OWNER_022', 'FUNCTIONAL_CLASS_026', 'YEAR_BUILT_027', 'TRAFFIC_LANES_ON_028A', 'TRAFFIC_LANES_UND_028B', 'ADT_029', 'YEAR_ADT_030', 'DESIGN_LOAD_031', 'APPR_WIDTH_MT_032', 'MEDIAN_CODE_033', 'DEGREES_SKEW_034', 'STRUCTURE_FLARED_035', 'RAILINGS_036A', 'TRANSITIONS_036B', 'APPR_RAIL_036C', 'APPR_RAIL_END_036D', 'HISTORY_037', 'NAVIGATION_038', 'NAV_VERT_CLR_MT_039', 'NAV_HORR_CLR_MT_040', 'OPEN_CLOSED_POSTED_041', 'SERVICE_ON_042A', 'SERVICE_UND_042B', 'STRUCTURE_KIND_043A', 'STRUCTURE_TYPE_043B', 'APPR_KIND_044A', 'APPR_TYPE_044B', 'MAIN_UNIT_SPANS_045', 'APPR_SPANS_046', 'HORR_CLR_MT_047', 'MAX_SPAN_LEN_MT_048', 'STRUCTURE_LEN_MT_049', 'LEFT_CURB_MT_050A', 'RIGHT_CURB_MT_050B', 'ROADWAY_WIDTH_MT_051', 'DECK_WIDTH_MT_052', 'VERT_CLR_OVER_MT_053', 'VERT_CLR_UND_REF_054A', 'VERT_CLR_UND_054B', 'LAT_UND_REF_055A', 'LAT_UND_MT_055B', 'LEFT_LAT_UND_MT_056', 'DECK_COND_058', 'SUPERSTRUCTURE_COND_059', 'SUBSTRUCTURE_COND_060', 'CHANNEL_COND_061', 'CULVERT_COND_062', 'OPR_RATING_METH_063', 'OPERATING_RATING_064', 'INV_RATING_METH_065', 'INVENTORY_RATING_066', 'STRUCTURAL_EVAL_067', 'DECK_GEOMETRY_EVAL_068', 'UNDCLRENCE_EVAL_069', 'POSTING_EVAL_070', 'WATERWAY_EVAL_071', 'APPR_ROAD_EVAL_072', 'WORK_PROPOSED_075A', 'WORK_DONE_BY_075B', 'IMP_LEN_MT_076', 'DATE_OF_INSPECT_090', 'INSPECT_FREQ_MONTHS_091', 'FRACTURE_092A', 'UNDWATER_LOOK_SEE_092B', 'SPEC_INSPECT_092C', 'FRACTURE_LAST_DATE_093A', 'UNDWATER_LAST_DATE_093B', 'SPEC_LAST_DATE_093C', 'BRIDGE_IMP_COST_094', 'ROADWAY_IMP_COST_095', 'TOTAL_IMP_COST_096', 'YEAR_OF_IMP_097', 'OTHER_STATE_CODE_098A', 'OTHER_STATE_PCNT_098B', 'OTHR_STATE_STRUC_NO_099', 'STRAHNET_HIGHWAY_100', 'PARALLEL_STRUCTURE_101', 'TRAFFIC_DIRECTION_102', 'TEMP_STRUCTURE_103', 'HIGHWAY_SYSTEM_104', 'FEDERAL_LANDS_105', 'YEAR_RECONSTRUCTED_106', 'DECK_STRUCTURE_TYPE_107', 'SURFACE_TYPE_108A', 'MEMBRANE_TYPE_108B', 'DECK_PROTECTION_108C', 'PERCENT_ADT_TRUCK_109', 'NATIONAL_NETWORK_110', 'PIER_PROTECTION_111', 'BRIDGE_LEN_IND_112', 'SCOUR_CRITICAL_113', 'FUTURE_ADT_114', 'YEAR_OF_FUTURE_ADT_115', 'MIN_NAV_CLR_MT_116', 'FED_AGENCY', 'SUBMITTED_BY', 'BRIDGE_CONDITION', 'LOWEST_RATING', 'DECK_AREA']

In [29]:
df.isnull().sum()

STATE_CODE_001          0
STRUCTURE_NUMBER_008    0
RECORD_TYPE_005A        0
ROUTE_PREFIX_005B       0
SERVICE_LEVEL_005C      0
                       ..
FED_AGENCY              0
SUBMITTED_BY            0
BRIDGE_CONDITION        0
LOWEST_RATING           0
DECK_AREA               0
Length: 123, dtype: int64

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3417 entries, 0 to 3416
Columns: 123 entries, STATE_CODE_001 to DECK_AREA
dtypes: float64(37), int64(52), object(34)
memory usage: 3.2+ MB

In [31]:
df.nunique().sort_values()

CRITICAL_FACILITY_006B       0
TEMP_STRUCTURE_103           0
OTHER_STATE_CODE_098A        0
YEAR_OF_IMP_097              0
WORK_DONE_BY_075B            1
                          ...
DECK_AREA                 2767
LOCATION_009              3007
LAT_016                   3356
LONG_017                  3363
STRUCTURE_NUMBER_008      3417
Length: 123, dtype: int64

In [37]:
constant_cols = [col for col in df.columns if df[col].nunique() <= 1]

print(constant_cols)
print("Total:", len(constant_cols))

['STATE_CODE_001', 'RECORD_TYPE_005A', 'YEAR_OF_IMP_097', 'OTHER_STATE_PCNT_098B', 'OTHR_STATE_STRUC_NO_099', 'TEMP_STRUCTURE_103', 'BRIDGE_LEN_IND_112', 'FED_AGENCY', 'SUBMITTED_BY']
Total: 9

In [38]:
df = df.drop(columns=constant_cols)

In [40]:
df.shape

(3417, 111)